# Generated by Django 5.2.7 on 2025-11-11 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip'), ('multi_city', 'Multi City')], max_length=20)),
                ('travel_class', models.CharField(choices=[('economy', 'Economy'), ('premium', 'Premium Economy'), ('buisness', 'Buisness'), ('first_class', 'First Class')], max_length=20)),
                ('depart_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('number_of_travelers', models.PositiveIntegerField(default=1)),
                ('service', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_booking', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_bookings', to='booking.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_bookings', to='booking.location')),
            ],
        ),
        migrations.CreateModel(
            name='MultiCitySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='booking.booking')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_destination', to='booking.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_origin', to='booking.location')),
            ],
        ),
    ]
